name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & SDKs
        run: |
          git clone --depth=1 --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks
          cd $HOME/theos/sdks
          for f in *.tar.xz; do tar -xf "$f" && rm "$f"; done
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          make clean
          make package FINALPACKAGE=1

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPALocker-Dylib
          path: |
            .theos/obj/*.dylib
            .theos/obj/FINALPACKAGE/*.dylib
            packages/*.deb
