name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & SDKs
        uses: Randomblock1/theos-action@v1

      - name: Build Dylib
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPALocker-Dylib
          path: |
            .theos/obj/*.dylib
            .theos/obj/FINALPACKAGE/*.dylib
            packages/*.deb
